<a href="https://colab.research.google.com/github/Abdullah1Jubair/CSE110/blob/main/CSE110Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1D Array**

In [ ]:
import numpy as np
array = np.array([1,2,3,4,5])
print("The array is:", array)
print("The dimension is:", array.ndim)
print("The Shape is:", array.shape)# shape matra show kore
print("The size is:", array.size)# size elements er length show kore

The array is: [1 2 3 4 5]
The dimension is: 1
The Shape is: (5,)
The size is: 5


**2D Array**




In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(array)
print("The dimension is:", array.ndim)
print("The shape is:", array.shape)
print("The size:", array.size)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
The dimension is: 2
The shape is: (2, 5)
The size: 10


In [ ]:
#Array Traversal
import numpy as np
array = np.array ([1, 2 , 3, 4, 5])
index = 0
while index< array.size:
  print(array[index],end= "")
  index = index+1

12345

**Array Creation from user**

In [ ]:
length = int(input("Please enter your array length: "))
array = np.zeros(length, dtype = int)

for i in range(length):
  value = int(input("Please enter your value: "))
  array[i] = value
print(array)

Please enter your array length: 5
Please enter your value: 1
Please enter your value: 2
Please enter your value: 3
Please enter your value: 4
Please enter your value: 5
[1 2 3 4 5]


**ARRAY Sorting**

In [ ]:
import numpy as np
array = np.array([7, 8, 9, 3, 2, 1])
for i in range(len(array)):
  for j in range(0,len(array)-i-1):
    if array[j]> array[j+1]:
      temp = array[j]
      array[j] = array[j+1]
      array[j+1] = temp
print("The final array is:",array)

The final array is: [1 2 3 7 8 9]


Take an integer N as an input from the user and create an 1D array with size N by taking each integer element as user input. Then, print the array. Next, take another integer input from the user. Resize the array and add the new integer value in the new array. Lastly, print the new array.

In [ ]:
import numpy as np
n = int(input())
array = np.zeros(n,dtype = int)
for i in range(n):
  elements = int(input())
  array[i] = elements
print(array)
new_array = np.zeros(n+1, dtype = int)
for j in range(n):
  new_array[j] = array[j]
new_array[-1]  = int(input())
print(new_array)

3
5
8
2
[5 8 2]
4
[5 8 2 4]


Take an integer N input from the user and create a 1D integer array of N numbers. Then, print the array. Next, modify the array by changing the positive numbers by 1 and the negative numbers by 0. If the element is zero, then it will be unchanged. Lastly, print the modified array.

In [ ]:
n = int(input())
import numpy as np
array = np.zeros(n, dtype = int)
for i in range(n):
  elements = int(input())
  array[i] = elements
print(array)
new_array = np.zeros(n,dtype= int)
for j in range(len(array)):
  if array[j]<0 :
    new_array[j] = 0
  elif array[j]>0:
    new_array[j] = 1
  elif array[j] == 0:
    new_array[j] = 0
print(new_array)

4
3
-2
1
0
[ 3 -2  1  0]
[1 0 1 0]


Write a Python function named reverseArray that takes a NumPy Array as parameter and using loop modifies & returns the reversed array within the given array. That means inside the function you can not create a new array.

In [ ]:

import numpy as np
def reverseArray(arr1):
  a = 0
  for i in range(arr1.size//2):
    a = arr1[i]
    arr1[i] = arr1[(arr1.size-1)-i]
    arr1[(arr1.size-1)-i] = a
  return arr1
arr1 = np.array([10, 12, 20, 5, 7])
arr1 = reverseArray(arr1)
print(arr1)

[ 7  5 20 12 10]


Write a Python function named printPairs that takes an array of numbers and a single integer value as parameters and prints the pairs of two array elements inside the function whose sum is equal to that integer value. If no such pair is found, then print "No Pair Found".

In [ ]:
import numpy as np
def printPairs(array,value):
  flag = False
  for i in range(array.size):
    for j in range(i+1,array.size):
      if array[i]+ array[j] == value:
        flag = True
        print(f"{array[i]},{array[j]}")
  if flag == False:
    print("No Pair Found")


arr1 = np.array([7,8,10,5,3,4,2])
printPairs(arr1, 15)

7,8
10,5


Suppose, you are given two 1D NumPy arrays (vectors). Now, using a loop, find the dot product of these two arrays and print the result. If the result is even, then swap the elements in the even index of the arrays. If the result is odd, then swap the elements in the odd index of the arrays. [You may assume that the size of both the arrays will be the same. Your code should work for 1D arrays of any size. You can not use in-built dot(), sum() or @ to solve this problem.]

In [ ]:
import numpy as np
vec1 = np.array([1,2,3,7])
vec2 = np.array([4,5,6,9])

dot_prod = 0
for i in range(vec1.size):
  dot_prod = dot_prod + vec1[i]*vec2[i]
print(dot_prod)
if dot_prod %2 == 0:
  for j in range(vec1.size):
    if j%2 == 0:
      vec1[j],vec2[j] = vec2[j],vec1[j]
  print(vec1)
  print(vec2)
else:
  for k in range(vec1.size):
    if j%2 ==1 :
      vec1[k],vec2[k] = vec2[k],vec1[k]
  print(vec1)
  print(vec2)



95
[1 2 3 7]
[4 5 6 9]


Take an integer N input from the user and create an 1D array of N numbers taking the elements as user input too. Then, print the array. Next, sort the array in the ascending order using Selection Sort technique. Lastly, print the sorted array.

In [ ]:
import numpy as np
n = int(input())
array = np.zeros(n, dtype = int)
for i in range(array.size):
  elements = int(input())
  array[i]= elements
print(array)
for j in range(array.size):
  min = array[j]
  for k in range(j+1,array.size):
    if array[k]<min:
      array[j] = array[k]
      array[k] = min
      min = array[j]

print(array)

6
3
6
1
2
8
9
[3 6 1 2 8 9]
[1 2 3 6 8 9]


Write a Python function called flatten that takes a 2D array as parameter and returns an 1D array by flattening the 2D array.

In [ ]:
import numpy as np
def flatten(array):
  row = array.shape[0]
  col = array.shape[1]
  new_array = np.zeros(array.size, dtype = int)
  index = 0

  for i in range(row):
    for j in range(col):
      new_array[index] = array[i][j]
      index = index+1
  return new_array

arr1 = np.array( [ [1, 2, 3],
                   [3, 4, 5] ] )
arr2 = flatten(arr1)
print(arr2)

[1 2 3 3 4 5]


You are given a square matrix A of size N×N. Check whether the given matrix is an Identity matrix or not. If it is, then print "Identity matrix" or otherwise print "Not an Identity matrix". Your program should work for any given 2D Arrays of size N×N.

In [ ]:
def identity(a):
  row = a.shape[0]
  flag = True
  for i in range(row):
    for j in range(row):
      if a[i][i] != 1:
        flag = False
        break
      if i != j:
        if a[i][j] != 0:
          flag = False
          break
  if flag == True:
    print("Identity Matrix")
  else:
    print("Not identity Matrix")
a = np.array([ [1, 0, 0],
               [0, 1, 0],
               [0, 0, 1] ])
identity(a)

Identity Matrix


You are given a 2D array A of size N×N. Print the absolute difference between the summation of its two diagonals (primary and secondary diagonal). Your program should work for any given 2D Arrays of size N×N.

In [ ]:
import numpy as np
def matrix (a) :
  primary = 0
  secondary = 0
  row = a.shape[0]
  for i in range(row):
    primary = primary + a[i][i]
    secondary = secondary + a[i][row-1-i]
    difference = abs(primary - secondary)
  print(difference)

A = np.array([ [1,  5,  12,  1],
                        [2,  -4,  6,  7],
                        [3,  8,  5,  9],
                        [3,  5,  23,  -6] ])
matrix(A)

22


Suppose, you are given a matrix of dimension M×N called A. You have to transpose the matrix in a new 2D array. Finally, print the new array. Your program should work for any given 2D Arrays of size M×N.